pipeline {
  agent {
    label 'fargate'
  }

  stages {
    stage('create-s3-bucket') {
      steps {
        withAWS(roleAccount:"${DEFAULT_ACCOUNT}", role:"${DEFAULT_ACCOUNT_JENKINS_ROLE}") {
          sh "aws cloudformation deploy --template-file sample/pipeline-s3/cfn-s3.yaml  --stack-name sample-s3-stack --parameter-overrides BucketName=jenkins-zzz-demox-${BUILD_NUMBER}"
        }
      }
    }
  }
}
